# Generated by Django 5.0.2 on 2024-02-21 23:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("username", models.CharField(max_length=30, unique=True)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="NewsStory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("headline", models.CharField(max_length=64)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pol", "Politics"),
                            ("art", "Art"),
                            ("tech", "Technologies"),
                            ("trivia", "Trivial"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("uk", "United Kingdom"),
                            ("eu", "European Union"),
                            ("w", "World"),
                        ],
                        max_length=30,
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("details", models.CharField(max_length=128)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news_agency.author",
                    ),
                ),
            ],
        ),
    ]
