# Generated by Django 5.0.2 on 2024-03-09 11:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("authorname", models.CharField(max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NewsStory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("headline", models.CharField(max_length=64)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pol", "Politics"),
                            ("art", "Art"),
                            ("tech", "Technologies"),
                            ("trivia", "Trivial"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("uk", "United Kingdom"),
                            ("eu", "European Union"),
                            ("w", "World"),
                        ],
                        max_length=30,
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("details", models.CharField(max_length=128)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.author"
                    ),
                ),
            ],
        ),
    ]
